using System.Text;
using System.Web;
using Microsoft.Extensions.Logging;
using Moka.Docs.Core.Api;
using Moka.Docs.Core.Content;
using Moka.Docs.Core.Pipeline;
using Moka.Docs.Engine.Phases;

namespace Moka.Docs.AspNetCore.Phases;

/// <summary>
///     Generates API reference pages from a pre-populated <see cref="BuildContext.ApiModel" />.
///     This phase runs after <c>CSharpAnalysisPhase</c> (order 300) and only activates
///     when <c>ApiModel</c> is already set (by the <see cref="InMemoryBuildOrchestrator" />)
///     but no API pages have been generated yet (because no C# projects were configured).
/// </summary>
public sealed class ReflectionApiPagePhase(
	ILogger<ReflectionApiPagePhase> logger) : IBuildPhase
{
	/// <inheritdoc />
	public string Name => "ReflectionApiPages";

	/// <inheritdoc />
	public int Order => 350; // After CSharpAnalysis (300), before MarkdownParse (400)

	/// <inheritdoc />
	public Task ExecuteAsync(BuildContext context, CancellationToken ct = default)
	{
		// Only run if ApiModel is pre-populated and no API pages exist yet
		if (context.ApiModel is null)
		{
			logger.LogDebug("No pre-populated ApiModel, skipping reflection API page generation");
			return Task.CompletedTask;
		}

		// Check if API pages were already generated by CSharpAnalysisPhase
		if (context.Pages.Any(p => p.Origin == PageOrigin.ApiGenerated))
		{
			logger.LogDebug("API pages already generated, skipping");
			return Task.CompletedTask;
		}

		GenerateApiPages(context);
		logger.LogInformation("Generated {Count} API pages from reflection model",
			context.Pages.Count(p => p.Origin == PageOrigin.ApiGenerated));

		return Task.CompletedTask;
	}

	/// <summary>
	///     Generates API index and per-type pages from the ApiModel.
	///     Mirrors the logic in CSharpAnalysisPhase.GenerateApiPages().
	/// </summary>
	private static void GenerateApiPages(BuildContext context)
	{
		if (context.ApiModel is null)
		{
			return;
		}

		// Generate API index page listing all namespaces and types
		var indexHtml = new StringBuilder();
		foreach (ApiNamespace ns in context.ApiModel.Namespaces)
		{
			indexHtml.AppendLine($"<h2>{HttpUtility.HtmlEncode(ns.Name)}</h2>");
			indexHtml.AppendLine("<div class=\"table-responsive\"><table class=\"api-member-table\">");
			indexHtml.AppendLine("<thead><tr><th>Name</th><th>Kind</th><th>Description</th></tr></thead>");
			indexHtml.AppendLine("<tbody>");
			foreach (ApiType type in ns.Types)
			{
				string route = $"/api/{ns.Name.Replace('.', '/')}/{type.Name}".ToLowerInvariant();
				string kindBadge = type.Kind.ToString().ToLowerInvariant();
				string summary = type.Documentation?.Summary ?? "";
				indexHtml.AppendLine("<tr>");
				indexHtml.AppendLine($"<td><a href=\"{route}\">{HttpUtility.HtmlEncode(type.Name)}</a></td>");
				indexHtml.AppendLine($"<td><span class=\"api-badge api-badge-{kindBadge}\">{type.Kind}</span></td>");
				indexHtml.AppendLine($"<td>{summary}</td>");
				indexHtml.AppendLine("</tr>");
			}

			indexHtml.AppendLine("</tbody>");
			indexHtml.AppendLine("</table></div>");
		}

		context.Pages.Add(new DocPage
		{
			FrontMatter = new FrontMatter { Title = "API Reference", Layout = "default" },
			Content = new PageContent { Html = indexHtml.ToString(), PlainText = "" },
			Route = "/api",
			Origin = PageOrigin.ApiGenerated
		});

		// Generate per-type pages
		var allTypes = context.ApiModel.Namespaces.SelectMany(n => n.Types).ToList();

		foreach (ApiNamespace ns in context.ApiModel.Namespaces)
		foreach (ApiType type in ns.Types)
		{
			string safeName = SanitizeRoutePart(type.Name);
			string route = $"/api/{ns.Name.Replace('.', '/')}/{safeName}".ToLowerInvariant();
			string apiHtml = ApiPageRenderer.RenderType(type, allTypes);
			TableOfContents toc = ApiPageRenderer.BuildTocForType(type);

			context.Pages.Add(new DocPage
			{
				FrontMatter = new FrontMatter
				{
					Title = type.Name,
					Description = type.Documentation?.Summary ?? $"API documentation for {type.FullName}",
					Layout = "default"
				},
				Content = new PageContent
				{
					Html = apiHtml,
					PlainText = type.Documentation?.Summary ?? ""
				},
				TableOfContents = toc,
				Route = route,
				Origin = PageOrigin.ApiGenerated
			});
		}
	}

	private static string SanitizeRoutePart(string name) =>
		name.Replace('<', '-').Replace('>', '-').Replace('`', '-').TrimEnd('-');
}
